#
# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT
#
# go to sleep after one hour (1*60*60*1000ms)

CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

CONFIG_ZMK_SLEEP=y





CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n

CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=160
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

# Uncomment the following line to enable NKRO
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Some operating systems have problems with full support for consumer keycodes.
# Uncomment the following line if keycodes labeled "consumer" like C_AC_SEARCH don't work
#CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Mouse enable
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_BACKLIGHT=y
CONFIG_ZMK_BACKLIGHT_BRT_START=100
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

#缩小数值减少延迟但对轴体品质要求会更高 Reducing the value will decrease the latency, but it will also place higher demands on the switching quality. If you are confident about the quality of the switch used on the keyboard, you can try smaller values, such as 1ms - 3ms.
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=2
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=2

#soft off
CONFIG_ZMK_PM_SOFT_OFF=y



# ==================================================
# nice!OLED DISPLAY
# LEFT / CENTRAL  : WPM 계기판 + 그래프, 고양이 없음
# RIGHT / PERIPHERAL : Bluetooth + Battery + GEM
# ==================================================

# ---------- LEFT / CENTRAL ----------

# WPM 표시
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=y

# 계기판
CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=y

# WPM 그래프
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE_MAX=100

# 고양이 / 캐릭터 OFF
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=n

# Caps Lock / Modifier 쪽에서도 고양이 OFF
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_LUNA=n
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_BONGO_CAT=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_LUNA=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_BONGO_CAT=n


# ---------- RIGHT / PERIPHERAL ----------

# Peripheral 애니메이션 사용
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=y

# GEM만 ON
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_GEM=y

# 다른 캐릭터 OFF
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_HEAD=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_POKEMON=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN=n

# 별도의 배터리 애니메이션 OFF
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SMART_BATTERY=n

# 정적 이미지 OFF
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL=n



